### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Nobodyno-boop** [DianoxDragon/Hawn#36]
Hi, error occured at the in-game setup n°2

```log
java.lang.IllegalArgumentException: /home/container/.\world_the_end\ does not exist
        at org.bukkit.craftbukkit.libs.org.apache.commons.io.FileUtils.checkDirectory(FileUtils.java:2692) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.libs.org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2579) ~[patched_1.16.5.jar:git-Paper-786]
        at fr.dianox.hawn.modules.world.GuiSystem.FirstPage(GuiSystem.java:842) ~[?:?]
        at fr.dianox.hawn.modules.admin.SetupUtils.Setup2World.lambda$0(Setup2World.java:89) ~[?:?]
        at fr.dianox.hawn.modules.admin.SetupUtils.Setup2World$$Lambda$4489/0x0000000074f1c020.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3125/0x00000000f5cbed20.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:883) [?:?]
```
Can be resolve by use `path.resolve()` 
at https://github.com/DianoxDragon/Hawn/blob/3bbded4434ca9ce53907eb7626a266c10e018121/src/fr/dianox/hawn/modules/world/GuiSystem.java#L842

sample example at : https://www.geeksforgeeks.org/path-resolve-method-in-java-with-examples/

**Comment by Nobodyno-boop** [comment]
Closed due to no response.
